---
title: "Lectures"
---

## Contents

|            | Date    | Title                                                     | Materials                                |
|----------------|----------------|------------------------|-----------------|
| Lecture 0  | June 3  | Welcome to SURE 2024                                      | [slides](lectures/00-welcome.qmd)        |
| Lecture 1  | June 4  | Exploring data: into the `tidyverse`                      | [slides](lectures/01-explore.qmd)        |
| Lecture 2  | June 5  | Data visualization: the grammar of graphics and `ggplot2` | [slides](lectures/02-graphics.qmd)       |
| Lecture 3  | June 6  | Data visualization: categorical data                      | [slides](lectures/03-categorical.qmd)    |
| Lecture 4  | June 7  | Data visualization: quantitative data                     | [slides](lectures/04-quantitative.qmd)   |
| Lecture 5  | June 10 | Unsupervised learning: $k$-means clustering               | [slides](lectures/05-kmeans.qmd)         |
| Lecture 6  | June 11 | Unsupervised learning: hierarchical clustering            | [slides](lectures/06-hierarchical.qmd)   |
| Lecture 7  | June 12 | Data visualization: density estimation                    | [slides](lectures/07-density.qmd)        |
| Lecture 8  | June 13 | Simulation                                                | [slides](lectures/08-simulation.qmd)     |
| Lecture 9  | June 14 | Presentations                                             | [slides](lectures/09-presentation.qmd)   |
| Lecture 10 | June 17 | Supervised learning: the tradeoffs                        | [slides](lectures/10-tradeoffs.qmd)      |
| Lecture 11 | June 21 | Supervised learning: linear regression                    | [slides](lectures/11-linear.qmd)         |
| Lecture 12 | June 24 | Supervised learning: variable selection                   | [slides](lectures/12-selection.qmd)      |
| Lecture 13 | June 25 | Supervised learning: regularization                       | [slides](lectures/13-regularization.qmd) |
| Lecture 14 | June 26 | Supervised learning: logistic regression                  | [slides](lectures/14-logistic.qmd)       |
| Lecture 15 | June 26 | Supervised learning: generalized linear models            | [slides](lectures/15-glm.qmd)            |
| Lecture 16 | June 27 | Unsupervised learning: principal component analysis       | [slides](lectures/16-pca.qmd)            |
| Lecture 17 | July 1  | Unsupervised learning: Gaussian mixture models            | [slides](lectures/17-mixture.qmd)        |
| Lecture 18 | July 2  | Supervised learning: nonparametric regression             | [slides](lectures/18-nonparametric.qmd)  |
| Lecture 19 | July 8  | Supervised learning: decision trees                       | [slides](lectures/19-trees.qmd)          |
| Lecture 20 | July 9  | Supervised learning: random forests and boosting          | [slides](lectures/20-forests.qmd)        |
| Lecture 21 | July 10 | Supervised learning: multinomial classification           | [slides](lectures/21-multinomial.qmd)    |

## References

-   [R for Data Science](https://r4ds.hadley.nz/)

-   [Modern Data Science with R](https://mdsr-book.github.io/mdsr3e/)

-   [Posit Cheatsheets](https://posit.co/resources/cheatsheets/)

-   [Quarto](https://quarto.org/)

-   [ggplot2](https://ggplot2.tidyverse.org/)

-   [TidyTuesday](https://github.com/rfordatascience/tidytuesday)

-   [Advanced Data Analysis from an Elementary Point of View](https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/)

-   [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/)

-   [An Introduction to Statistical Learning](https://www.statlearning.com/)

-   [The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/)

-   [More recommended R books](https://www.rstudio.com/resources/books/)
