{
  "hash": "4f9ec6ab1c13d8b78926f468e5190599",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supervised learning: variable selection\"\nauthor: \"<br>SURE 2024<br><br>Department of Statistics & Data Science<br>Carnegie Mellon University\"\nfooter:  \"[36-SURE.github.io/2024](https://36-sure.github.io/2024)\"\nformat:\n  revealjs:\n    theme: theme.scss\n    chalkboard: true\n    smaller: true\n    slide-number: c/t\n    code-line-numbers: false\n    linestretch: 1.25\n    html-math-method:\n      method: mathjax\n      url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n---\n\n\n\n\n\n\n# Background\n\n## Setting\n\nSuppose we wish to learn a linear model. Our estimate (denoted by hats) is\n$$\n\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_1 + \\cdots + \\hat{\\beta}_p X_p\n$$\n\n. . .\n\nWhy would we attempt to select a __subset__ of the $p$ variables?\n\n. . .\n\n- *To improve prediction accuracy* \n\n  - Eliminating uninformative predictors can lead to lower variance in the test set MSE, at the expense of a slight increase in bias\n\n. . .\n\n- *To improve model interpretability*\n\n  - Eliminating uninformative predictors is obviously a good thing when your goal is to tell the story of how your predictors are associated with your response.\n\n\n## Best subset selection\n\n- Start with the __null model__ $\\mathcal{M}_0$ (intercept-only) that has no predictors\n  - Predict the sample mean for each observation\n  \n. . .\n\n- For $k = 1, 2, \\dots, p$ (each possible number of predictors)\n  - Fit __all__ $\\displaystyle \\binom{p}{k} = \\frac{p!}{k!(p-k)!}$ with exactly $k$ predictors\n  - Pick the best among these $\\displaystyle \\binom{p}{k}$ models, call it $\\mathcal{M}_k$\n    - \"Best\" can be based on cross-validation error, highest adjusted $R^2$, etc.\n    - \"It depends on your loss function\"\n  \n. . .\n\n- Select a single best model from among $\\mathcal{M}_0, \\dots, \\mathcal{M}_p$\n\n## Best subset selection\n\n__This is not typically used in research!__\n\n- only practical for a smaller number of variables\n\n- computationally infeasible for a large number of predictors\n\n- arbitrary way of defining __best__ and ignores __prior knowledge__ about potential predictors\n\n\n## Use the shoe leather approach\n\nDo not turn off your brain!\n\n- algorithms can be tempting but they are NOT substitutes!\n- you should NOT avoid the hard work of EDA in your modeling efforts\n\n. . .\n\n__Variable selection is a difficult problem!__\n\n- Like much of a statistics research, there is not one unique, correct answer\n\n. . .\n\nJustify which predictors used in modeling based on:\n\n- __domain knowledge__\n- __context__\n- __extensive EDA__\n- __model assessment based on holdout predictions__\n\n\n:::aside\nRecommended reading: David A. Freedman (1991). *Statistical Models and Shoe Leather*\n:::\n\n## Covariance and correlation\n\n- __Covariance__ is a measure of the __linear__ dependence between two variables\n\n  - To be _\"uncorrelated\"_ is not the same as to be _\"independent\"_...\n  \n  - Independence means __there is no dependence__, linear or otherwise\n  \n  - If two variables are independent, then they are also uncorrelated. However, if two variables are uncorrelated, then they can still be dependent.\n  \n  - [Recommended reading](https://www.stat.cmu.edu/~cshalizi/uADA/13/reminders/uncorrelated-vs-independent.pdf)\n  \n\n. . .\n\n- __Correlation__ is a _normalized_ form of covariance, ranges from -1 to 1\n\n  - -1 means one variable linearly decreases absolutely in value while the other increases\n  \n  - 0 means no linear dependence\n  \n  - 1 means one variable linear increases absolutely while the other increases\n\n# Case study\n\n## Data: [Hollywood Movies (2012-2018)](https://rdrr.io/cran/Lock5Data/man/HollywoodMovies.html)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_light())\nmovies <- read_csv(\"https://raw.githubusercontent.com/36-SURE/2024/main/data/movies.csv\")\nglimpse(movies)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,295\nColumns: 15\n$ Movie            <chr> \"2016: Obama's America\", \"21 Jump Street\", \"A Late Qu…\n$ LeadStudio       <chr> \"Rocky Mountain Pictures\", \"Sony Pictures Releasing\",…\n$ RottenTomatoes   <dbl> 26, 85, 76, 90, 35, 27, 91, 56, 11, 44, 93, 63, 87, 9…\n$ AudienceScore    <dbl> 73, 82, 71, 82, 51, 72, 62, 47, 47, 63, 82, 51, 63, 9…\n$ Genre            <chr> \"Documentary\", \"Comedy\", \"Drama\", \"Drama\", \"Horror\", …\n$ TheatersOpenWeek <dbl> 1, 3121, 9, 7, 3108, 3039, 132, 245, 2539, 3192, 3, 1…\n$ OpeningWeekend   <dbl> 0.03, 36.30, 0.08, 0.04, 16.31, 24.48, 1.14, 0.70, 11…\n$ BOAvgOpenWeekend <dbl> 30000, 11631, 8889, 5714, 5248, 8055, 8636, 2857, 449…\n$ Budget           <dbl> 3.0, 42.0, NA, NA, 68.0, 12.0, NA, 7.5, 35.0, 50.0, 1…\n$ DomesticGross    <dbl> 33.35, 138.45, 1.56, 1.55, 37.52, 70.01, 1.99, 3.01, …\n$ WorldGross       <dbl> 33.35, 202.81, 6.30, 7.60, 137.49, 82.50, 3.59, 8.54,…\n$ ForeignGross     <dbl> 0.00, 64.36, 4.74, 6.05, 99.97, 12.49, 1.60, 5.53, 9.…\n$ Profitability    <dbl> 1334.00, 482.88, NA, NA, 202.19, 687.50, NA, 113.87, …\n$ OpenProfit       <dbl> 1.20, 86.43, NA, NA, 23.99, 204.00, NA, 9.33, 32.57, …\n$ Year             <dbl> 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012,…\n```\n\n\n:::\n\n```{.r .cell-code}\nmovies <- movies |> \n  janitor::clean_names() |> \n  select(audience_score, rotten_tomatoes, theaters_open_week, opening_weekend, budget, domestic_gross, foreign_gross) |> \n  drop_na()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n## Modeling audience rating\n\nInterested in modeling the audience rating of a movie\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmovies |> \n  ggplot(aes(x = audience_score)) +\n  geom_histogram(fill = \"gray\", color = \"white\")\n```\n\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/score-diff-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Correlation matrix of audience score and candidate predictors\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- Interested in `audience_score` relationships with critics rating, opening weekend statistics, budget, gross income of viewers\n\n- Plot correlation matrix with `ggcorrplot`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# can also use corrr package\n# library(corrr)\n# movies |> \n#   correlate(diagonal = 1) |> # get correlation matrix\n#   stretch() |>  # similar to pivot_longer\n#   ggplot(aes(x, y, fill = r)) +\n#   geom_tile()\nlibrary(ggcorrplot)\nmovies_cor <- cor(movies)\nggcorrplot(movies_cor)\n```\n:::\n\n\n\n\n\n:::\n\n\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n\n\n\n## Customize the appearance of the correlation matrix\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- Avoid redundancy by only using one half of matrix with `type`\n\n- Add correlation value labels using `lab` (but round first!)\n\n- Can arrange variables based on clustering...\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmovies_cor |> \n  round(2) |> \n  ggcorrplot(hc.order = TRUE, type = \"lower\", lab = TRUE)\n```\n:::\n\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n\n\n\n## Clustering variables using the correlation matrix\n\nApply hierarchical clustering to variables instead of observations\n\n\n. . .\n\n- Select the explanatory variables of interest from our data\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmovies_feat <- movies |> \n  select(-audience_score)\n```\n:::\n\n\n\n\n. . .\n\n- Compute correlation matrix of these variables\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfeat_cor <- cor(movies_feat)\n```\n:::\n\n\n\n\n. . .\n\n- Correlations measure similarity and can be negative __BUT__ distances measure dissimilarity and __CANNOT__\n\n- Convert your correlations to all be $\\geq 0$: e.g., $1 - |\\rho|$ (which drops the sign) or $1 - \\rho$\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor_dist_matrix <- 1 - abs(feat_cor)\n```\n:::\n\n\n\n\n. . .\n\n- Convert to distance matrix before using `hclust`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor_dist_matrix <- as.dist(cor_dist_matrix)\n```\n:::\n\n\n\n\n\n## Clustering variables using the correlation matrix\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- Cluster variables using `hclust()` as before\n\n- Use [`ggdendro`](https://cran.r-project.org/web/packages/ggdendro/vignettes/ggdendro.html) to quickly visualize dendrogram\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggdendro)\nmovies_feat_hc <- hclust(cor_dist_matrix, \"complete\")\nggdendrogram(movies_feat_hc,\n             rotate = TRUE,\n             size = 2)\n```\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n\n\n\n## Clustering variables using the correlation matrix\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n- Another flexible option is [`dendextend`](https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dendextend)\ncor_dist_matrix |>\n  hclust() |>\n  as.dendrogram() |>\n  set(\"branches_k_col\", k = 2) |>\n  set(\"labels_cex\", 1) |>\n  ggplot(horiz = TRUE)\n```\n:::\n\n\n\n\n- Explore the [package documentation](https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html) for more formatting\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n:::\n:::\n\n\n\n## Back to the response variable...\n\nPairs plot using [`GGally`](https://ggobi.github.io/ggally/index.html)\n\n- __always look at your data__\n\n- correlation values alone are not enough!\n\n- what if a variable displayed a nonlinear (e.g. quadratic) relationship?\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(GGally)\nggpairs(movies)\n```\n:::\n\n\n\n\n## Back to the response variable...\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=1344}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n## Which variables matter for modeling audience rating?\n\n. . .\n\nUse __10-fold cross-validation__ to assess how well different sets of variables perform in predicting `audience_score`?\n\n\n. . .\n\nCreate a column of __test__ fold assignments to our dataset with the `sample()` function:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(100)\nk <- 10\nmovies <- movies |>\n  mutate(test_fold = sample(rep(1:k, length.out = n())))\n\n# table(movies$test_fold)  \n```\n:::\n\n\n\n\n\n. . .\n\n__Always remember to `set.seed()` prior to performing $k$-fold cross-validation!__\n\n\n\n## Writing a function for $k$-fold cross-validation\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_cv_pred <- function(model_formula, data = movies) {\n  # generate holdout predictions for every row\n  get_test_pred <- function(fold) {\n  \n    # separate test and training data\n  \n    test_data <- data |> filter(test_fold == fold)\n    train_data <- data |> filter(test_fold != fold)\n    train_fit <- lm(as.formula(model_formula), data = train_data)\n  \n    # return test results\n    test_res <- tibble(test_pred = predict(train_fit, newdata = test_data),\n                       test_actual = test_data$audience_score,\n                       test_fold = fold)\n    return(test_res)\n  }\n  \n  test_pred <- map(1:k, get_test_pred) |> \n    bind_rows()\n  \n  return(test_pred)\n}\n```\n:::\n\n\n\n\n\n\n\n\n## Function enables easy generation of holdout analysis\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_pred <- get_cv_pred(\n  \"audience_score ~ rotten_tomatoes + theaters_open_week + opening_weekend + budget + domestic_gross + foreign_gross\"\n)\nall_no_critics_pred <- get_cv_pred(\n  \"audience_score ~ theaters_open_week + opening_weekend + budget + domestic_gross + foreign_gross\"\n)\ncritics_only_pred <- get_cv_pred(\"audience_score ~ rotten_tomatoes\")\nopening_only_pred <- get_cv_pred(\"audience_score ~ budget + theaters_open_week + opening_weekend + rotten_tomatoes\")\ngross_only_pred <- get_cv_pred(\"audience_score ~ domestic_gross + foreign_gross + rotten_tomatoes\")\nint_only_pred <- get_cv_pred(\"audience_score ~ 1\")\n```\n:::\n\n\n\n\n. . .\n\n::: columns\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\nCan then summarize together for a single plot:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  mutate(all_pred, mod = \"All\"),\n  mutate(all_no_critics_pred, mod = \"All but critics\"),\n  mutate(critics_only_pred, mod = \"Critics only\"),\n  mutate(opening_only_pred, mod = \"Opening only\"),\n  mutate(gross_only_pred, mod = \"Gross income only\"),\n  mutate(int_only_pred, mod = \"Intercept only\")\n) |>\n  group_by(mod) |>\n  summarize(\n    rmse = sqrt(mean((test_actual - test_pred)^2))\n  ) |>\n  mutate(mod = fct_reorder(mod, rmse)) |>\n  ggplot(aes(x = rmse, y = mod)) +\n  geom_point()\n```\n:::\n\n\n\n\n\n:::\n\n::: {.column width=\"50%\" style=\"text-align: left;\"}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n:::\n:::\n\n## Fit selected model on all data and view summary\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_fit <- lm(\n  audience_score ~ rotten_tomatoes + theaters_open_week + opening_weekend + budget + domestic_gross + foreign_gross, \n  data = movies\n)\n# summary(all_fit)\nlibrary(broom)\nall_fit |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  term               estimate std.error statistic   p.value\n  <chr>                 <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        40.5      1.35        29.9   1.66e-142\n2 rotten_tomatoes     0.395    0.0160      24.7   1.74e-106\n3 theaters_open_week -0.00214  0.000393    -5.44  6.55e-  8\n4 opening_weekend    -0.114    0.0362      -3.16  1.62e-  3\n5 budget              0.0168   0.0116       1.45  1.46e-  1\n6 domestic_gross      0.0690   0.0125       5.52  4.16e-  8\n7 foreign_gross       0.00415  0.00497      0.835 4.04e-  1\n```\n\n\n:::\n:::\n\n\n\n\n. . .\n\n* But... do NOT show a coefficients table in a presentation (well... it depends)\n\n* A nicely formatted table of the summary output is more appropriate in a written report\n\n* Packages that can take a model object and produce a neat table summary: `kableExtra`, `texreg`, `modelsummary`, `gtsummary`, `huxtable`, `sjPlot`\n\n## Coefficient plot (with uncertainty quantification)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_fit |> \n  tidy(conf.int = TRUE) |> \n  filter(term != \"(Intercept)\") |> \n  ggplot(aes(x = estimate, y = term))  +\n  geom_point(size = 4) +\n  geom_errorbar(aes(xmin = conf.low, xmax = conf.high, width = 0.2)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\")\n```\n\n::: {.cell-output-display}\n![](12-selection_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=1920}\n:::\n:::\n\n\n\n\n:::aside\nIt's also called a dot-and-whisker plot or forest plot or blobbogram\n:::\n\n<!-- - Use `ggcoef()` from `GGally` package -->\n<!-- ```{r ggcoef, fig.width=18} -->\n<!-- all_fit |>  -->\n<!--   ggcoef(exclude_intercept = TRUE, vline = TRUE, vline_color = \"red\") -->\n<!-- ``` -->\n\n## Interpretation\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_fit |> tidy(conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 7\n  term               estimate std.error statistic   p.value conf.low conf.high\n  <chr>                 <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)        40.5      1.35        29.9   1.66e-142 37.8      43.1    \n2 rotten_tomatoes     0.395    0.0160      24.7   1.74e-106  0.363     0.426  \n3 theaters_open_week -0.00214  0.000393    -5.44  6.55e-  8 -0.00291  -0.00137\n4 opening_weekend    -0.114    0.0362      -3.16  1.62e-  3 -0.186    -0.0434 \n5 budget              0.0168   0.0116       1.45  1.46e-  1 -0.00587   0.0395 \n6 domestic_gross      0.0690   0.0125       5.52  4.16e-  8  0.0445    0.0935 \n7 foreign_gross       0.00415  0.00497      0.835 4.04e-  1 -0.00560   0.0139 \n```\n\n\n:::\n:::\n\n\n\n\n. . .\n\nFor `rotten_tomatoes`:\n\n*   Coefficient interpretation: Among the Hollywood movies, each additional score in Rotten Tomatoes rating is associated with a 0.395 higher score in audience rating, on average ((95% CI [0.363, 0.426]))\n\n*   Test for the coefficient: With $t=24.7$ and $p$-value $<0.001$, we have sufficient evidence that audience rating and Rotten Tomatoes critic rating are related, after accounting for other variables in the model (i.e. there was a statistically significant association between audience and critic ratings).\n\n# Making tables\n\n## `broom::tidy()`and `kable()`\n\nSee also: [`kableExtra`](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_fit |> \n  tidy() |> \n  knitr::kable(digits = 3,\n               col.names = c(\"Term\", \"Estimate\", \"SE\", \"t\", \"p-value\"))\n```\n\n::: {.cell-output-display}\n\n\n|Term               | Estimate|    SE|      t| p-value|\n|:------------------|--------:|-----:|------:|-------:|\n|(Intercept)        |   40.456| 1.353| 29.890|   0.000|\n|rotten_tomatoes    |    0.395| 0.016| 24.691|   0.000|\n|theaters_open_week |   -0.002| 0.000| -5.442|   0.000|\n|opening_weekend    |   -0.114| 0.036| -3.161|   0.002|\n|budget             |    0.017| 0.012|  1.454|   0.146|\n|domestic_gross     |    0.069| 0.012|  5.525|   0.000|\n|foreign_gross      |    0.004| 0.005|  0.835|   0.404|\n\n\n:::\n:::\n\n\n\n\n## `broom::tidy()`and `gt()`\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gt)\nall_fit |> \n  tidy() |> \n  gt() |> \n  fmt_number(columns = where(is.numeric), decimals = 2) |> \n  cols_label(term = \"Term\",\n             estimate = \"Estimate\",\n             std.error = \"SE\",\n             statistic = \"t\",\n             p.value = md(\"*p*-value\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"unqpvqmcmb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#unqpvqmcmb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#unqpvqmcmb thead, #unqpvqmcmb tbody, #unqpvqmcmb tfoot, #unqpvqmcmb tr, #unqpvqmcmb td, #unqpvqmcmb th {\n  border-style: none;\n}\n\n#unqpvqmcmb p {\n  margin: 0;\n  padding: 0;\n}\n\n#unqpvqmcmb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#unqpvqmcmb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#unqpvqmcmb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#unqpvqmcmb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#unqpvqmcmb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#unqpvqmcmb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#unqpvqmcmb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#unqpvqmcmb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#unqpvqmcmb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#unqpvqmcmb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#unqpvqmcmb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#unqpvqmcmb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#unqpvqmcmb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#unqpvqmcmb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#unqpvqmcmb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unqpvqmcmb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#unqpvqmcmb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#unqpvqmcmb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#unqpvqmcmb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unqpvqmcmb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#unqpvqmcmb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unqpvqmcmb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#unqpvqmcmb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unqpvqmcmb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#unqpvqmcmb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#unqpvqmcmb .gt_left {\n  text-align: left;\n}\n\n#unqpvqmcmb .gt_center {\n  text-align: center;\n}\n\n#unqpvqmcmb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#unqpvqmcmb .gt_font_normal {\n  font-weight: normal;\n}\n\n#unqpvqmcmb .gt_font_bold {\n  font-weight: bold;\n}\n\n#unqpvqmcmb .gt_font_italic {\n  font-style: italic;\n}\n\n#unqpvqmcmb .gt_super {\n  font-size: 65%;\n}\n\n#unqpvqmcmb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#unqpvqmcmb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#unqpvqmcmb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#unqpvqmcmb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#unqpvqmcmb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#unqpvqmcmb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#unqpvqmcmb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Term\">Term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t\">t</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;em&gt;p&lt;/em&gt;-value\"><em>p</em>-value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">40.46</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.35</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">29.89</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">rotten_tomatoes</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.39</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">24.69</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">theaters_open_week</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−5.44</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">opening_weekend</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.11</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.04</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−3.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">budget</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.01</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1.45</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.15</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">domestic_gross</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.07</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.01</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.52</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">foreign_gross</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.84</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.40</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## [`gtsummary`](https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html)\n\nUse `tbl_regression()` function\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nall_fit |> \n  tbl_regression() |> \n  bold_p() |> \n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"trfxdximuq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#trfxdximuq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#trfxdximuq thead, #trfxdximuq tbody, #trfxdximuq tfoot, #trfxdximuq tr, #trfxdximuq td, #trfxdximuq th {\n  border-style: none;\n}\n\n#trfxdximuq p {\n  margin: 0;\n  padding: 0;\n}\n\n#trfxdximuq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#trfxdximuq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#trfxdximuq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#trfxdximuq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#trfxdximuq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#trfxdximuq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#trfxdximuq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#trfxdximuq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#trfxdximuq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#trfxdximuq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#trfxdximuq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#trfxdximuq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#trfxdximuq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#trfxdximuq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#trfxdximuq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#trfxdximuq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#trfxdximuq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#trfxdximuq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#trfxdximuq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#trfxdximuq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#trfxdximuq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#trfxdximuq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#trfxdximuq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#trfxdximuq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#trfxdximuq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#trfxdximuq .gt_left {\n  text-align: left;\n}\n\n#trfxdximuq .gt_center {\n  text-align: center;\n}\n\n#trfxdximuq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#trfxdximuq .gt_font_normal {\n  font-weight: normal;\n}\n\n#trfxdximuq .gt_font_bold {\n  font-weight: bold;\n}\n\n#trfxdximuq .gt_font_italic {\n  font-style: italic;\n}\n\n#trfxdximuq .gt_super {\n  font-size: 65%;\n}\n\n#trfxdximuq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#trfxdximuq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#trfxdximuq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#trfxdximuq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#trfxdximuq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#trfxdximuq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#trfxdximuq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">rotten_tomatoes</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.39</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.36, 0.43</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">theaters_open_week</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.00</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.00, 0.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">opening_weekend</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.11</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.19, -0.04</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">budget</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.01, 0.04</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.15</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">domestic_gross</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.04, 0.09</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">foreign_gross</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.00</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.01, 0.01</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n## [`gt`](https://gt.rstudio.com/) (and [`gtExtras`](https://jthomasmock.github.io/gtExtras/))\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://gt.rstudio.com/reference/figures/gt_parts_of_a_table.svg){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n:::aside\nThere are also [other `R` packages for making tables](https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html)\n:::\n\n## A `gt` example\n\nFor more in-depth tutorials, see [here](https://themockup.blog/posts/2020-05-16-gt-a-grammar-of-tables/) and [here](https://jthomasmock.github.io/gtExtras/articles/plotting-with-gtExtras.html)\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# https://bradcongelio.com/nfl-analytics-with-r-book/04-nfl-analytics-visualization.html\ncpoe <- read_csv(\"http://nfl-book.bradcongelio.com/pure-cpoe\")\ncpoe_gt <- cpoe |> \n  select(passer, season, total_attempts, mean_cpoe) |> \n  gt(rowname_col = \"passer\") |> \n  fmt_number(columns = c(mean_cpoe), decimals = 2) |>\n  data_color(columns = c(mean_cpoe),\n             fn = scales::col_numeric(palette = c(\"#FEE0D2\", \"#67000D\"), domain = NULL)) |> \n  cols_align(align = \"center\", columns = c(\"season\", \"total_attempts\")) |> \n  tab_stubhead(label = \"Quarterback\") |> \n  cols_label(season = \"Season\",\n             total_attempts = \"Attempts\",\n             mean_cpoe = \"Mean CPOE\") |> \n  tab_header(title = md(\"**Average CPOE in Pure Passing Situations**\"),\n             subtitle = md(\"*For seasons between 2010 and 2022*\")) |> \n  tab_source_note(source_note = md(\"Example adapted from the book<br>*An Introduction to NFL Analytics with R*\")) |> \n  gtExtras::gt_theme_espn()\n\n# gtsave(cpoe_gt, \"cpoe_gt.png\")\n```\n:::\n\n\n\n\n## A `gt` example\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lcuglbejgv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#lcuglbejgv table {\n  font-family: Lato, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lcuglbejgv thead, #lcuglbejgv tbody, #lcuglbejgv tfoot, #lcuglbejgv tr, #lcuglbejgv td, #lcuglbejgv th {\n  border-style: none;\n}\n\n#lcuglbejgv p {\n  margin: 0;\n  padding: 0;\n}\n\n#lcuglbejgv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: #FFFFFF;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lcuglbejgv .gt_title {\n  color: #333333;\n  font-size: 24px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lcuglbejgv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lcuglbejgv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lcuglbejgv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lcuglbejgv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lcuglbejgv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lcuglbejgv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lcuglbejgv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lcuglbejgv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lcuglbejgv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lcuglbejgv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lcuglbejgv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lcuglbejgv .gt_row {\n  padding-top: 7px;\n  padding-bottom: 7px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #F6F7F7;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lcuglbejgv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lcuglbejgv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lcuglbejgv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lcuglbejgv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lcuglbejgv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lcuglbejgv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lcuglbejgv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lcuglbejgv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_striped {\n  background-color: #FAFAFA;\n}\n\n#lcuglbejgv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lcuglbejgv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lcuglbejgv .gt_sourcenote {\n  font-size: 12px;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lcuglbejgv .gt_left {\n  text-align: left;\n}\n\n#lcuglbejgv .gt_center {\n  text-align: center;\n}\n\n#lcuglbejgv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lcuglbejgv .gt_font_normal {\n  font-weight: normal;\n}\n\n#lcuglbejgv .gt_font_bold {\n  font-weight: bold;\n}\n\n#lcuglbejgv .gt_font_italic {\n  font-style: italic;\n}\n\n#lcuglbejgv .gt_super {\n  font-size: 65%;\n}\n\n#lcuglbejgv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lcuglbejgv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lcuglbejgv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lcuglbejgv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lcuglbejgv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lcuglbejgv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lcuglbejgv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style><strong>Average CPOE in Pure Passing Situations</strong></td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style><em>For seasons between 2010 and 2022</em></td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Quarterback\">Quarterback</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Season\">Season</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Attempts\">Attempts</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mean CPOE\">Mean CPOE</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">P.Rivers</th>\n<td headers=\"stub_1_1 season\" class=\"gt_row gt_center\">2013</td>\n<td headers=\"stub_1_1 total_attempts\" class=\"gt_row gt_center\">291</td>\n<td headers=\"stub_1_1 mean_cpoe\" class=\"gt_row gt_right\" style=\"background-color: #67000D; color: #FFFFFF;\">10.89</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">P.Mahomes</th>\n<td headers=\"stub_1_2 season\" class=\"gt_row gt_center gt_striped\">2018</td>\n<td headers=\"stub_1_2 total_attempts\" class=\"gt_row gt_center gt_striped\">261</td>\n<td headers=\"stub_1_2 mean_cpoe\" class=\"gt_row gt_right gt_striped\" style=\"background-color: #AB6459; color: #FFFFFF;\">9.29</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">A.Rodgers</th>\n<td headers=\"stub_1_3 season\" class=\"gt_row gt_center\">2020</td>\n<td headers=\"stub_1_3 total_attempts\" class=\"gt_row gt_center\">242</td>\n<td headers=\"stub_1_3 mean_cpoe\" class=\"gt_row gt_right\" style=\"background-color: #C78C7F; color: #FFFFFF;\">8.57</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">R.Wilson</th>\n<td headers=\"stub_1_4 season\" class=\"gt_row gt_center gt_striped\">2013</td>\n<td headers=\"stub_1_4 total_attempts\" class=\"gt_row gt_center gt_striped\">231</td>\n<td headers=\"stub_1_4 mean_cpoe\" class=\"gt_row gt_right gt_striped\" style=\"background-color: #CB9184; color: #FFFFFF;\">8.47</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">R.Wilson</th>\n<td headers=\"stub_1_5 season\" class=\"gt_row gt_center\">2018</td>\n<td headers=\"stub_1_5 total_attempts\" class=\"gt_row gt_center\">277</td>\n<td headers=\"stub_1_5 mean_cpoe\" class=\"gt_row gt_right\" style=\"background-color: #CC9386; color: #FFFFFF;\">8.45</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">D.Brees</th>\n<td headers=\"stub_1_6 season\" class=\"gt_row gt_center gt_striped\">2011</td>\n<td headers=\"stub_1_6 total_attempts\" class=\"gt_row gt_center gt_striped\">311</td>\n<td headers=\"stub_1_6 mean_cpoe\" class=\"gt_row gt_right gt_striped\" style=\"background-color: #D29C8F; color: #000000;\">8.29</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\">M.Ryan</th>\n<td headers=\"stub_1_7 season\" class=\"gt_row gt_center\">2018</td>\n<td headers=\"stub_1_7 total_attempts\" class=\"gt_row gt_center\">315</td>\n<td headers=\"stub_1_7 mean_cpoe\" class=\"gt_row gt_right\" style=\"background-color: #D49F91; color: #000000;\">8.23</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\">M.Ryan</th>\n<td headers=\"stub_1_8 season\" class=\"gt_row gt_center gt_striped\">2012</td>\n<td headers=\"stub_1_8 total_attempts\" class=\"gt_row gt_center gt_striped\">303</td>\n<td headers=\"stub_1_8 mean_cpoe\" class=\"gt_row gt_right gt_striped\" style=\"background-color: #D9A698; color: #000000;\">8.11</td></tr>\n    <tr><th id=\"stub_1_9\" scope=\"row\" class=\"gt_row gt_left gt_stub\">R.Wilson</th>\n<td headers=\"stub_1_9 season\" class=\"gt_row gt_center\">2015</td>\n<td headers=\"stub_1_9 total_attempts\" class=\"gt_row gt_center\">279</td>\n<td headers=\"stub_1_9 mean_cpoe\" class=\"gt_row gt_right\" style=\"background-color: #EFC8BA; color: #000000;\">7.52</td></tr>\n    <tr><th id=\"stub_1_10\" scope=\"row\" class=\"gt_row gt_left gt_stub\">J.Burrow</th>\n<td headers=\"stub_1_10 season\" class=\"gt_row gt_center gt_striped\">2021</td>\n<td headers=\"stub_1_10 total_attempts\" class=\"gt_row gt_center gt_striped\">343</td>\n<td headers=\"stub_1_10 mean_cpoe\" class=\"gt_row gt_right gt_striped\" style=\"background-color: #FEE0D2; color: #000000;\">7.12</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\">Example adapted from the book<br><em>An Introduction to NFL Analytics with R</em></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n",
    "supporting": [
      "12-selection_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}