---
title: "EDA project: hepatitis"
---

---

## Overview

This project will be released on Thursday, June 6 and **conclude with a 10-minute presentation on Tuesday, June 18 during lecture time**.

Students will be randomly placed into groups of three and each group will be randomly assigned a dataset.

The goal of this project is to practice understanding the structure of a dataset, and to practice generating and evaluating hypotheses using fundamental EDA and data visualization techniques.

## Deliverables

Each group is expected to make slides to accompany the 10-minute presentation.

The presentation should feature the following:

-   Overview of the structure of your dataset

-   **Three questions/hypotheses** you are interested in exploring

-   **Three data visualizations** exploring the questions, at least two of which must be multivariate. **Each visualization must be in a different format** from the other two, and you must have at least one categorical and one continuous visualization

-   **One clustering analysis**

-   Conclusions reached for the hypotheses based on your EDA and data visualizations

## Timeline

There will be two submission deadlines:

**Thursday, June 13 at 5pm ET** - Each student will push their individual code for the project thus far to GitHub for review. We will then provide feedback.

**Monday, June 17 at 5pm ET** - Slides and full code must be completed and ready for presentation. Send your slides to Quang ([`quang@stat.cmu.edu`](mailto:quang@stat.cmu.edu)). All code must be written in `R`; but the slides may be created in any software. Take advantage of examples from lectures, but also feel free to explore online resources that may be relevant.

## Data

This datasets contains laboratory measurements of blood donors and Hepatitis C patients. The data were obtained from the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/HCV+data), with the original source coming from the article [*Using machine learning techniques to generate laboratory diagnostic pathways—a case study*](https://jlpm.amegroups.org/article/view/4401/5425), published in Journal of Laboratory and Precision Medicine.

Each row in the dataset represents a patient and the columns are:

-   `...1`: patient ID number
-   `Category`: diagnosis (`0=Blood Donor`, `0s=suspect Blood Donor`, `1=Hepatitis`, `2=Fibrosis`, `3=Cirrhosis`)
-   `Age`: age (in years)
-   `Sex`: sex (male or female)
-   `ALB`: albumin blood test
-   `ALP`: alkaline phosphatase
-   `ALT`: alanine transaminase
-   `AST`: aspartate transaminase
-   `BIL`: bilirubin
-   `CHE`: acetylcholinesterase
-   `CHOL`: cholesterol
-   `CREA`: creatinine
-   `GGT`: gamma-glutamyl transferase
-   `PROT`: proteins

## Starter code

```{r, eval=FALSE}
library(tidyverse)
hepatitis <- read_csv("https://raw.githubusercontent.com/36-SURE/36-SURE.github.io/main/data/hepatitis.csv")
```