---
title: "EDA project: PHF shooting"
---

---

## Overview

This project will be released on Thursday, June 6 and **conclude with a 10-minute presentation (+ 2-3 minutes for Q&A) on Tuesday, June 18 (either during the morning session from x to x or in the afternoon from x to x)**.

The goal of this project is to practice understanding the structure of a dataset, and to practice generating and evaluating hypotheses using fundamental EDA and data visualization techniques.

## Deliverables

Your team is expected to make slides to accompany your 12-minute presentation.

<!-- The timing is strict; you will only have no more than 12 minutes to present.  -->

The presentation should feature the following:

-   Overview of the structure of your dataset

-   **Three questions/hypotheses** you are interested in exploring

-   **Three data visualizations** exploring the questions, at least two of which must be multivariate. **Each visualization must be in a different format** from the other two, and you must have at least one categorical and one continuous visualization

-   **One clustering analysis**

-   Conclusions reached for the hypotheses based on your EDA and data visualizations

## Timeline

There will be two submission deadlines:

**Thursday, June 13 at 5pm ET** - Each student will push their individual code for the project thus far to their GitHub accounts for review. We will then provide feedback on the code submitted.

**Monday, June 17 at 11:59pm ET** - Slides and full code must be completed and ready for presentation. Send your slides to Quang ([`quang@stat.cmu.edu`](mailto:quang@stat.cmu.edu)). All code must be written in `R`. Take advantage of examples from lectures, but also feel free to explore material online that may be relevant!

## Data

This dataset contains shot information during the 2021-2022 PHF season. The [Premier Hockey Federation (PHF)](https://www.premierhockeyfederation.com/) (2015-2023) was a professional women's ice hockey league in North America. Recently, more data has become available for people to explore and join the [women's hockey analytics community](https://www.whkyhac.com/). The data were collected using the [`fastRhockey` package in `R`](https://fastrhockey.sportsdataverse.org/index.html) and include the following columns:

-   `play_description`: string detailed description of event
-   `play_type`: string denoting the outcome of the shot, either `Goal`, `PP Goal` (meaning power play goal), `SH Goal`, (meaning shorthanded goal), `Shot` (shot saved by goalie), or `Shot BLK` (meaning blocked by a non-goalie)
-   `period_id`: integer value of the game period
-   `time_remaining` String display of time remaining in period in `MM:SS` format where `MM` and `SS` denotes minutes and seconds remaning respectively
-   `sec_from_start` Numeric value of the seconds since the start of the game
-   `home_team`: string name of the home team
-   `away_team`: string name of the away team
-   `home_goals`: integer value of the home team score after the event
-   `away_goals`: integer value of the away team score after the event
-   `shooting_team`: string defining the team taking the shot
-   `player_name_1`: string name of the player taking the shot
-   `player_name_2`: string name of the secondary event player (blocker or goalie)
-   `goalie_involved`: string name of the goalie involved in the shot attempt
-   `shot_result`: string denoting the outcome of the shot, either `blocked` (meaning blocked by a non-goalie), `made` (goal), or `saved` (shot on net that was saved by a goalie)
-   `on_ice_situation`: string indicator for game strength: `Even Strength` or `Power Play`
-   `home_score_total`: integer value of the home team score at the end of the game
-   `away_score_total`: integer value of the away team score at the end of the game

## Starter code

```{r, eval = FALSE}
library(tidyverse)
library(fastRhockey)
phf_pbp <- load_phf_pbp(2021)
phf_shots <- phf_pbp |> 
  # do not include miss, these were only recorded for a few game
  filter(play_type %in% c("Goal", "PP Goal", "SH Goal", "Shot", "Shot BLK")) %>%
  select(play_description, play_type, period_id, time_remaining, 
         sec_from_start, home_team, away_team, home_goals, away_goals, 
         shooting_team = team, player_name_1, player_name_2, goalie_involved,
         shot_result, on_ice_situation, home_score_total, away_score_total)
```